<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EventusTestProject>false</EventusTestProject>
    <RootNamespace>Eventus.Testing</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.14.0" />
    <PackageReference Include="Npgsql" Version="10.0.2" />
    <PackageReference Include="Testcontainers.RabbitMq" Version="4.14.0" />
    <PackageReference Include="Testcontainers.MongoDb" Version="4.14.0" />
    <PackageReference Include="Testcontainers.Kafka" Version="4.14.0" />
    <PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
  </ItemGroup>
</Project>
