services:
  account-db:
    image: postgres:17-alpine

  catalog-db:
    image: postgres:17-alpine

  identity-db:
    image: mongo:8.0.4

  rabbitmq:
    image: rabbitmq:4-management-alpine

  kafka:
    image: apache/kafka:3.9.0

  pgadmin:
    image: dpage/pgadmin4:latest

  account:
    image: account
    build:
      context: .
      dockerfile: Account/Dockerfile

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Catalog/Catalog.API/Dockerfile

  catalog.grpc:
    image: catalog.grpc
    build:
      context: .
      dockerfile: Catalog/Catalog.GRPC/Dockerfile

  game:
    image: game
    build:
      context: .
      dockerfile: Game/Dockerfile

  identity.api:
    image: identity.api
    build:
      context: .
      dockerfile: Identity/Identity.API/Dockerfile

  api.gateway:
    image: api.gateway
    build:
      context: .
      dockerfile: API.Gateway/Dockerfile

volumes:
  account-db_data:
  catalog-db_data:
  identity-db_data:
  rabbitmq_data:
  kafka_data:
  pgadmin_data:
