services:
  account:
    image: account
    build:
      context: .
      dockerfile: Account/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      game:
        condition: service_started

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Catalog/Catalog.API/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      catalog-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  catalog.grpc:
    image: catalog.grpc
    build:
      context: .
      dockerfile: Catalog/Catalog.GRPC/Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      catalog-db:
        condition: service_healthy

  account-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventus_account
    ports:
      - "5433:5432"
    volumes:
      - account-db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  catalog-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventus_catalog
    ports:
      - "5432:5432"
    volumes:
      - catalog-db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - catalog-db

  game:
    image: game
    build:
      context: .
      dockerfile: Game/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      catalog.grpc:
        condition: service_started

  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  api.gateway:
    image: api.gateway
    build:
      context: .
      dockerfile: API.Gateway/Dockerfile
    ports:
      - "1234:8080"
    depends_on:
      account:
        condition: service_started
      game:
        condition: service_started
      catalog.api:
        condition: service_started
      identity.api:
        condition: service_started

  identity.api:
    image: identity.api
    build:
      context: .
      dockerfile: Identity/Identity.API/Dockerfile
    ports:
      - "8084:8080"
    depends_on:
      - identity-db

  identity-db:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - identity-db_data:/data/db

volumes:
  catalog-db_data:
  account-db_data:
  rabbitmq_data:
  identity-db_data:
