syntax = "proto3";

option csharp_namespace = "Catalog.GRPC";

package catalog;

service Catalog {
  rpc GetEventPrice (GetEventPriceRequest) returns (GetEventPriceResponse);
  rpc UpdateEventPrice (UpdateEventPriceRequest) returns (UpdateEventPriceResponse);
}

message GetEventPriceRequest {
  string event_id = 1;
}
message GetEventPriceResponse {
  string pot = 6;
  string pool_yes = 7;
  string pool_no = 8;
  string price_yes = 9;
  string price_no = 10;
  
  reserved 1;
  reserved 2;
  reserved 3;
  reserved 4;
  reserved 5;
}

message UpdateEventPriceRequest {
  string event_id = 1;
  string pool_yes = 7;
  string pool_no = 8;
  string pot = 9;

  reserved 2;
  reserved 3;
  reserved 4;
  reserved 5;
  reserved 6;
}

message UpdateEventPriceResponse {
  bool success = 1;
}
