<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\Common.Messaging\Common.Messaging.csproj" />
    <ProjectReference Include="..\..\Common.Web\Common.Web.csproj" />
    <ProjectReference Include="..\Testing.Common\Testing.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
